"""尚未接入全国主表的 2025 年城市统计公报和预算执行来源。

这些来源均为可定位的官方网页/附件或交易所公开披露的精确转载摘录。
未披露的字段不设置模式，避免用其他行政范围或推算值代填。
"""

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RAW_DIR = ROOT / "raw" / "province_fiscal" / "2025"


def _source(
    *,
    city_name: str,
    city_id: str,
    slug: str,
    url: str,
    path: str,
    text_path: str,
    publisher: str,
    publication_date: str,
    source_grade: str,
    patterns: dict[str, str],
    source_format: str = "html",
    data_status: str = "execution",
    data_status_label: str | None = None,
    note: str,
) -> dict:
    return {
        "year": 2025,
        "city_name": city_name,
        "city_id": city_id,
        "source_doc_id": f"SRC-2025-CURATED-{slug}",
        "url": url,
        "path": RAW_DIR / path,
        "text_path": RAW_DIR / text_path,
        "text_is_curated": True,
        "document_title": f"{city_name}2025年统计公报或预算执行报告",
        "publisher": publisher,
        "publisher_level": "市级统计/财政机构" if source_grade == "A2" else "交易所公开披露的B2精确转载",
        "publication_date": publication_date,
        "source_grade": source_grade,
        "source_format": source_format,
        "raw_unit": "亿元",
        "raw_units": {
            "gdp_real_growth_pct": "%",
            "resident_population_10k": "万人",
        },
        "data_status": data_status,
        "data_status_label": data_status_label or "2025年执行数（精确来源）",
        "document_type": "城市统计公报/财政预算执行报告（精确摘录）",
        "page_number": "正文或定位摘录",
        "page_count": "1",
        "patterns": patterns,
        "note": note,
    }


CURATED_2025_CITY_FISCAL_SOURCES = (
    _source(
        city_name="阿克苏地区", city_id="CN-652900", slug="AKSU",
        url="https://www.crei.cn/file/br.aspx?id=20260528085809&op=sczz&x=0",
        path="official/aksu_2025_statistical_bulletin.html",
        text_path="official/aksu_2025_economic_fiscal_excerpt.txt",
        publisher="阿克苏地区统计局（精确转载）", publication_date="2026-05-28", source_grade="B2",
        patterns={
            "gdp_current_100m": r"生产总值（GDP）([0-9.]+)亿元",
            "gdp_real_growth_pct": r"生产总值（GDP）[0-9.]+亿元.*?增长([0-9.]+)%",
            "general_public_revenue_100m": r"一般公共预算收入([0-9.]+)亿元",
            "general_public_expenditure_100m": r"一般公共预算支出([0-9.]+)亿元",
        },
        note="B2精确转载；全地区口径，未披露年末常住人口和政府性基金收入，二者保持为空。",
    ),
    _source(
        city_name="巴音郭楞蒙古自治州", city_id="CN-652800", slug="BAZHOU",
        url="https://www.crei.cn/file/br.aspx?id=20260528085331&op=sczz&x=0",
        path="official/bazhou_2025_statistical_bulletin.html",
        text_path="official/bazhou_2025_statistical_bulletin_excerpt.txt",
        publisher="巴音郭楞蒙古自治州统计局（精确转载）", publication_date="2026-05-28", source_grade="B2",
        patterns={
            "gdp_current_100m": r"巴州地区实现生产总值（GDP）([0-9.]+)亿元",
            "gdp_real_growth_pct": r"巴州地区实现生产总值（GDP）[0-9.]+亿元.*?增长([0-9.]+)%",
            "resident_population_10k": r"年末全州常住人口（不含铁门关市）([0-9.]+)万人",
            "general_public_revenue_100m": r"地方一般公共预算收入([0-9.]+)亿元",
            "general_public_expenditure_100m": r"地方一般公共预算支出([0-9.]+)亿元",
        },
        note="B2精确转载；GDP、财政为巴州全州口径，人口明确不含铁门关市，政府性基金收入未披露。",
    ),
    _source(
        city_name="博尔塔拉蒙古自治州", city_id="CN-652700", slug="BOZHOU",
        url="https://www.xjboz.gov.cn/xjboz/c125800/202604/119d224f1920458fb81d8de4ae48fb54.shtml",
        path="official/bozhou_2025_statistical_bulletin.html",
        text_path="official/bozhou_2025_statistical_bulletin_excerpt.txt",
        publisher="博尔塔拉蒙古自治州统计局", publication_date="2026-04-01", source_grade="A2",
        patterns={
            "gdp_current_100m": r"地区生产总值([0-9.]+)亿元",
            "gdp_real_growth_pct": r"地区生产总值[0-9.]+亿元.*?同比增长([0-9.]+)%",
            "general_public_revenue_100m": r"一般公共预算收入([0-9.]+)亿元",
            "general_public_expenditure_100m": r"一般公共预算支出([0-9.]+)亿元",
            "gov_fund_revenue_100m": r"政府性基金预算收入([0-9.]+)亿元",
        },
        note="A2官方统计公报；博州全州口径，人口未明确披露。",
    ),
    _source(
        city_name="常德市", city_id="CN-430700", slug="CHANGDE",
        url="https://www.cdsrd.gov.cn/rdhy/rmdbdh/iqajifnqaf/gzbg05/content_3158113",
        path="official/changde_2025_budget_report.html",
        text_path="official/changde_2025_budget_report_excerpt.txt",
        publisher="常德市财政局/常德市人大常委会", publication_date="2026-01-30", source_grade="A2",
        data_status_label="2025年预计执行数",
        patterns={
            "general_public_revenue_100m": r"地方一般公共预算收入预计完成([0-9.]+)亿元",
            "general_public_expenditure_100m": r"一般公共预算支出([0-9.]+)亿元",
            "gov_fund_revenue_100m": r"政府性基金预算收入完成([0-9.]+)亿元",
        },
        note="A2官方人大网页定位摘录；财政字段为全市口径预计执行数，保留execution/预计状态。",
    ),
    _source(
        city_name="昌吉回族自治州", city_id="CN-652300", slug="CHANGJI",
        url="https://www.crei.cn/file/br.aspx?id=20260508105148",
        path="official/changji_2025_statistical_bulletin.html",
        text_path="official/changji_2025_statistical_bulletin_excerpt.txt",
        publisher="昌吉回族自治州统计局（精确转载）", publication_date="2026-05-08", source_grade="B2",
        patterns={
            "gdp_current_100m": r"地区生产总值（GDP）([0-9.]+)亿元",
            "gdp_real_growth_pct": r"地区生产总值（GDP）[0-9.]+亿元.*?增长([0-9.]+)%",
            "general_public_revenue_100m": r"一般公共预算收入([0-9.]+)亿元",
            "general_public_expenditure_100m": r"一般公共预算支出([0-9.]+)亿元",
        },
        note="B2精确转载；昌吉州全州口径，人口和政府性基金收入未披露。",
    ),
    _source(
        city_name="长沙市", city_id="CN-430100", slug="CHANGSHA-STATISTICAL",
        url="https://tjj.hunan.gov.cn/hntj/tjfx/tjgb/szgb/zss_1/202605/t20260512_33975356.html",
        path="official/changsha_2025_statistical_bulletin.html",
        text_path="official/changsha_2025_statistical_bulletin_excerpt.txt",
        publisher="湖南省统计局", publication_date="2026-05-12", source_grade="A2",
        patterns={
            "gdp_current_100m": r"地区生产总值([0-9.]+)亿元",
            "gdp_real_growth_pct": r"地区生产总值[0-9.]+亿元.*?增长([0-9.]+)%",
            "general_public_revenue_100m": r"地方一般公共预算收入([0-9.]+)亿元",
            "general_public_expenditure_100m": r"一般公共预算支出([0-9.]+)亿元",
        },
        note="A2官方统计公报；经济财政为长沙市全市口径，政府性基金收入由已有独立财政来源保留。",
    ),
    _source(
        city_name="常州市", city_id="CN-320400", slug="CHANGZHOU",
        url="https://rd.changzhou.gov.cn/html/rd/2026/EKPMKPDC_0122/35038.html",
        path="official/changzhou_2025_budget_report.html",
        text_path="official/changzhou_2025_budget_report_excerpt.txt",
        publisher="常州市财政局/常州市人大常委会", publication_date="2026-01-22", source_grade="A2",
        data_status_label="2025年预计执行数",
        patterns={
            "general_public_revenue_100m": r"一般公共预算收入完成([0-9.]+)亿元",
            "general_public_expenditure_100m": r"一般公共预算支出完成([0-9.]+)亿元",
            "gov_fund_revenue_100m": r"政府性基金预算收入完成([0-9.]+)亿元",
        },
        note="A2官方人大网页定位摘录；三项财政字段为全市预计执行数，保留execution/预计状态。",
    ),
    _source(
        city_name="福州市", city_id="CN-350100", slug="FUZHOU-FINAL",
        url="https://www.fuzhou.gov.cn/zgfzzt/czzj/bjndyjs/zfjsgk/202607/t20260713_5345722.htm",
        path="official/fuzhou_2025_finance_final.html",
        text_path="official/fuzhou_2025_finance_final_excerpt.txt",
        publisher="福州市财政局", publication_date="2026-07-13", source_grade="A2",
        data_status="final", data_status_label="2025年财政决算数",
        patterns={
            "general_public_revenue_100m": r"全市一般公共预算收入([0-9.]+)亿元",
            "general_public_expenditure_100m": r"一般公共预算支出([0-9.]+)亿元",
            "gov_fund_revenue_100m": r"全市政府性基金预算收入([0-9.]+)亿元",
        },
        note="A2官方财政决算公开页；采用福州市全市（含平潭）决算收支数，不使用加上转移性收支后的决算结果。",
    ),
    _source(
        city_name="哈密市", city_id="CN-650500", slug="HAMI",
        url="https://www.hami.gov.cn/hami/c120173/202605/9bc459f53d3d4abda752ae0e967cf68a.shtml",
        path="official/hami_2025_statistical_bulletin.html",
        text_path="official/hami_2025_statistical_bulletin_excerpt.txt",
        publisher="哈密市统计局、国家统计局哈密调查队", publication_date="2026-05-01", source_grade="A2",
        patterns={
            "gdp_current_100m": r"地区生产总值（GDP）([0-9.]+)亿元",
            "gdp_real_growth_pct": r"地区生产总值（GDP）[0-9.]+亿元.*?增长([0-9.]+)%",
            "general_public_revenue_100m": r"一般公共预算收入完成([0-9.]+)亿元",
            "general_public_expenditure_100m": r"一般公共预算支出([0-9.]+)亿元",
        },
        note="A2官方统计公报；哈密市全市口径，人口和政府性基金收入未披露。",
    ),
    _source(
        city_name="衡阳市", city_id="CN-430400", slug="HENGYANG",
        url="https://www.hengyang.gov.cn/czj/ztxx/czysjsgk/cxzyhyjsgk/ysjsbg/20260115/i3850020.html",
        path="official/hengyang_2025_budget_report_excerpt.txt",
        text_path="official/hengyang_2025_budget_report_excerpt.txt",
        publisher="衡阳市财政局", publication_date="2026-01-15", source_grade="A2",
        data_status_label="2025年预计执行数",
        patterns={
            "general_public_revenue_100m": r"地方一般公共预算收入([0-9.]+)亿元",
            "general_public_expenditure_100m": r"一般公共预算支出([0-9.]+)亿元",
            "gov_fund_revenue_100m": r"政府性基金预算收入([0-9.]+)亿元",
        },
        note="A2官方财政网页定位摘录；三项财政字段为全市口径，收入和支出标注预计完成数。",
    ),
    _source(
        city_name="喀什地区", city_id="CN-653100", slug="KASHGAR",
        url="https://www.kashi.gov.cn/ksdqxzgs/c112198/202604/4eb6af2f3cda49a8baa7df45973b6f21.shtml",
        path="official/kashgar_2025_statistical_bulletin.html",
        text_path="official/kashgar_2025_economic_fiscal_excerpt.txt",
        publisher="喀什地区统计局、国家统计局喀什调查队", publication_date="2026-04-01", source_grade="A2",
        patterns={
            "gdp_current_100m": r"地区生产总值（GDP）([0-9.]+)亿元",
            "gdp_real_growth_pct": r"地区生产总值（GDP）[0-9.]+亿元.*?增长([0-9.]+)%",
            "general_public_revenue_100m": r"一般公共预算收入完成([0-9.]+)亿元",
            "general_public_expenditure_100m": r"一般公共预算支出([0-9.]+)亿元",
        },
        note="A2官方统计公报；喀什地区全地区口径，人口和政府性基金收入未披露。",
    ),
    _source(
        city_name="青岛市", city_id="CN-370200", slug="QINGDAO",
        url="https://www.qingdao.gov.cn/zwgk/zdgk/czxx/szfyjs/zxqk/202601/P020260130338555114519.pdf",
        path="official/qingdao_2025_budget_report.pdf",
        text_path="official/qingdao_2025_budget_report_excerpt.txt",
        publisher="青岛市财政局", publication_date="2026-01-30", source_grade="A2", source_format="pdf",
        patterns={
            "general_public_revenue_100m": r"一般公共预算收入完成([0-9.]+)亿元",
            "general_public_expenditure_100m": r"一般公共预算支出完成([0-9.]+)亿元",
            "gov_fund_revenue_100m": r"政府性基金预算收入完成([0-9.]+)亿元",
        },
        note="A2官方财政附件精确摘录；三项财政字段为青岛市全市执行数。",
    ),
    _source(
        city_name="泉州市", city_id="CN-350500", slug="QUANZHOU",
        url="https://www.quanzhou.gov.cn/zfb/xxgk/zfxxgkzl/qzdt/qzyw/202603/t20260331_3279339.htm",
        path="official/quanzhou_2025_statistical_bulletin.html",
        text_path="official/quanzhou_2025_statistical_bulletin_excerpt.txt",
        publisher="泉州市统计局、国家统计局泉州调查队", publication_date="2026-03-31", source_grade="A2",
        patterns={
            "gdp_current_100m": r"地区生产总值([0-9.]+)亿元",
            "gdp_real_growth_pct": r"地区生产总值[0-9.]+亿元.*?增长([0-9.]+)%",
            "general_public_revenue_100m": r"其中地方一般公共预算收入([0-9.]+)亿元",
            "general_public_expenditure_100m": r"一般公共预算支出([0-9.]+)亿元",
            "gov_fund_revenue_100m": r"政府性基金预算收入([0-9.]+)亿元",
        },
        note="A2官方统计公报；财政收入采用明确标注的地方一般公共预算收入，不使用一般公共预算总收入。",
    ),
    _source(
        city_name="苏州市", city_id="CN-320500", slug="SUZHOU-STATISTICAL",
        url="https://www.suzhou.gov.cn/szsrmzf/ndgmjjhshfztjsjfb/202605/0543af82405748cd9ffa4cfc81aecccd.shtml",
        path="official/suzhou_2025_statistical_bulletin.html",
        text_path="official/suzhou_2025_statistical_bulletin_excerpt.txt",
        publisher="苏州市统计局", publication_date="2026-05-01", source_grade="A2",
        patterns={
            "gdp_current_100m": r"地区生产总值([0-9.]+)亿元",
            "gdp_real_growth_pct": r"地区生产总值[0-9.]+亿元.*?增长([0-9.]+)%",
            "resident_population_10k": r"年末常住人口([0-9.]+)万人",
            "general_public_revenue_100m": r"一般公共预算收入([0-9.]+)亿元",
            "general_public_expenditure_100m": r"一般公共预算支出([0-9.]+)亿元",
        },
        note="A2官方统计公报；经济财政为苏州市全市口径，政府性基金收入由已有独立财政来源保留。",
    ),
    _source(
        city_name="吐鲁番市", city_id="CN-650400", slug="TURPAN",
        url="https://www.tlf.gov.cn/tlfs/c106274/202604/5dac049b5b88481b8363227e425e73d5.shtml",
        path="official/turpan_2025_statistical_bulletin.html",
        text_path="official/turpan_2025_statistical_bulletin_excerpt.txt",
        publisher="吐鲁番市统计局", publication_date="2026-04-01", source_grade="A2",
        patterns={
            "gdp_current_100m": r"地区生产总值\(GDP\)([0-9.]+)亿元",
            "gdp_real_growth_pct": r"地区生产总值\(GDP\)[0-9.]+亿元.*?增长([0-9.]+)%",
            "resident_population_10k": r"年末全市常住人口([0-9.]+)万人",
            "general_public_revenue_100m": r"一般公共预算收入([0-9.]+)亿元",
            "general_public_expenditure_100m": r"一般公共预算支出([0-9.]+)亿元",
        },
        note="A2官方统计公报；吐鲁番市全市口径，政府性基金收入未披露。",
    ),
    _source(
        city_name="无锡市", city_id="CN-320200", slug="WUXI",
        url="https://rd.wuxi.gov.cn/doc/2026/01/30/4726147.shtml",
        path="official/wuxi_2025_budget_report.html",
        text_path="official/wuxi_2025_budget_report_excerpt.txt",
        publisher="无锡市财政局/无锡市人大常委会", publication_date="2026-01-30", source_grade="A2",
        data_status_label="2025年预计执行数",
        patterns={
            "general_public_revenue_100m": r"一般公共预算收入完成([0-9.]+)亿元",
            "general_public_expenditure_100m": r"一般公共预算支出完成([0-9.]+)亿元",
            "gov_fund_revenue_100m": r"政府性基金预算收入完成([0-9.]+)亿元",
        },
        note="A2官方人大网页定位摘录；三项财政字段为无锡市全市预计执行数。",
    ),
    _source(
        city_name="益阳市", city_id="CN-430900", slug="YIYANG",
        url="https://www.yiyang.gov.cn/czj/5841/5844/5860/content_2143608.html",
        path="official/yiyang_2025_budget_report.html",
        text_path="official/yiyang_2025_budget_report_excerpt.txt",
        publisher="益阳市财政局", publication_date="2026-01-30", source_grade="A2",
        data_status_label="2025年预计执行数",
        patterns={
            "general_public_revenue_100m": r"地方一般公共预算收入([0-9.]+)亿元",
            "general_public_expenditure_100m": r"一般公共预算支出([0-9.]+)亿元",
            "gov_fund_revenue_100m": r"政府性基金预算收入([0-9.]+)亿元",
        },
        note="A2官方财政网页定位摘录；三项财政字段为益阳市全市口径，收入标注预计完成数。",
    ),
    _source(
        city_name="沈阳市", city_id="CN-210100", slug="SHENYANG",
        url="https://www.crei.cn/file/br.aspx?id=20260522102711&op=sczz&x=0",
        path="secondary/shenyang_2025_statistical_bulletin.html",
        text_path="secondary/shenyang_2025_statistical_bulletin_excerpt.txt",
        publisher="沈阳市统计局（精确转载）", publication_date="2026-05-22", source_grade="B2",
        patterns={
            "general_public_revenue_100m": r"一般公共预算收入([0-9.]+)亿元",
            "general_public_expenditure_100m": r"一般公共预算支出([0-9.]+)亿元",
        },
        note="B2精确公报转载；沈阳市全市财政口径，GDP、人口和政府性基金收入未在本摘录披露。",
    ),
    _source(
        city_name="扬州市", city_id="CN-321000", slug="YANGZHOU",
        url="https://www.crei.cn/file/br.aspx?id=20260527164838",
        path="secondary/yangzhou_2025_statistical_bulletin.html",
        text_path="secondary/yangzhou_2025_statistical_bulletin_excerpt.txt",
        publisher="扬州市统计局（精确转载）", publication_date="2026-05-27", source_grade="B2",
        patterns={
            "gdp_current_100m": r"生产总值([0-9.]+)亿元",
            "gdp_real_growth_pct": r"生产总值[0-9.]+亿元.*?增长([0-9.]+)%",
            "resident_population_10k": r"年末全市常住人口([0-9.]+)万人",
            "general_public_revenue_100m": r"一般公共预算收入([0-9.]+)亿元",
            "general_public_expenditure_100m": r"一般公共预算支出([0-9.]+)亿元",
            "gov_fund_revenue_100m": r"政府性基金预算收入([0-9.]+)亿元",
        },
        note="B2精确表格转载；扬州市全市口径，政府性基金收入为原文明确附列值。",
    ),
    _source(
        city_name="镇江市", city_id="CN-321100", slug="ZHENJIANG",
        url="https://www.crei.cn/file/br.aspx?id=20260527164608&op=zc&x=0",
        path="secondary/zhenjiang_2025_statistical_bulletin.html",
        text_path="secondary/zhenjiang_2025_statistical_bulletin_excerpt.txt",
        publisher="镇江市统计局（精确转载）", publication_date="2026-05-27", source_grade="B2",
        patterns={
            "gdp_current_100m": r"地区生产总值([0-9.]+)亿元",
            "gdp_real_growth_pct": r"地区生产总值[0-9.]+亿元.*?增长([0-9.]+)%",
            "general_public_revenue_100m": r"一般公共预算收入([0-9.]+)亿元",
            "general_public_expenditure_100m": r"一般公共预算支出([0-9.]+)亿元",
        },
        note="B2精确表格转载；镇江市全市口径，人口和政府性基金收入未在本摘录披露。",
    ),
    _source(
        city_name="江门市", city_id="CN-440700", slug="JIANGMEN-FUND",
        url="https://www.jiangmen.gov.cn/attachment/0/375/375866/3447145.pdf",
        path="official/jiangmen_2025_budget_execution_report.pdf",
        text_path="official/jiangmen_2025_budget_execution_report_excerpt.txt",
        publisher="江门市财政局", publication_date="2026-02-25", source_grade="A2",
        source_format="pdf",
        patterns={"gov_fund_revenue_100m": r"全市政府性基金预算收入([0-9.]+)亿元"},
        note="A2官方预算执行报告；仅接入明确的全市政府性基金预算收入，不使用市本级口径。",
    ),
    _source(
        city_name="海口市", city_id="CN-460100", slug="HAIKOU-STATISTICAL",
        url="https://www.crei.cn",
        path="secondary/haikou_2025_statistical_bulletin.html",
        text_path="secondary/haikou_2025_statistical_bulletin_excerpt.txt",
        publisher="海口市统计局（精确转载）", publication_date="2026-05-01", source_grade="B2",
        patterns={
            "gdp_current_100m": r"地区生产总值([0-9.]+)亿元",
            "gdp_real_growth_pct": r"地区生产总值[0-9.]+亿元.*?增长([0-9.]+)%",
            "general_public_revenue_100m": r"地方一般公共预算收入([0-9.]+)亿元",
            "general_public_expenditure_100m": r"地方一般公共预算支出([0-9.]+)亿元",
        },
        note="B2精确统计公报转载；经济财政为海口市全市口径，政府性基金收入由已有A2财政来源保留。",
    ),
)
