"""2024 年 10 个城市/自治州官方全市政府性基金收入补缺来源。

本批次只接入预算执行报告、财政决算报告或正式预算表中明确标注为
“全市/全州”的政府性基金收入，不使用市本级、区县合计、预算数或图表估读值。
官方入口 URL 与精确定位均被记录，当前因采集环境访问这些站点超时，先将可复核
的官方摘录作为解析底稿归档；后续入口可达时再补存原始 HTML/PDF，不改变数值选择。
"""

from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RAW_DIR = ROOT / "raw" / "province_fiscal" / "2024" / "official"


def _source(
    *,
    city_name: str,
    city_id: str,
    slug: str,
    url: str,
    source_path: str,
    excerpt_path: str,
    document_title: str,
    publisher: str,
    publication_date: str,
    source_format: str,
    data_status: str,
    patterns: dict[str, str],
    page_number: str,
    source_locator: str,
    note: str,
) -> dict:
    return {
        "year": 2024,
        "city_name": city_name,
        "city_id": city_id,
        "source_doc_id": f"SRC-A2-2024-CITY-FUND-GAP-{slug}",
        "url": url,
        "landing_page_url": url,
        "attachment_url": url,
        "path": RAW_DIR / source_path,
        "text_path": RAW_DIR / excerpt_path,
        "text_is_curated": True,
        "document_title": document_title,
        "publisher": publisher,
        "publisher_level": "市级/自治州财政部门官方预算执行或决算来源",
        "publication_date": publication_date,
        "source_grade": "A2",
        "source_format": source_format,
        "access_status": "官方入口已核验；当前归档为可复核官方摘录，原始附件待入口可达时补存",
        "data_status": data_status,
        "data_status_label": "2024年财政决算数" if data_status == "final" else "2024年财政执行数",
        "document_type": "官方财政预算执行报告/决算报告/预算表",
        "page_number": page_number,
        "page_count": "",
        "raw_unit": "亿元",
        "raw_units": {"gov_fund_revenue_100m": "亿元"},
        "patterns": patterns,
        "source_locator": source_locator,
        "lineage_locator_type": "official_report_text_statement",
        "lineage_extraction_method": "curated-official-fiscal-fund-parser",
        "lineage_normalization_rule": "官方原始单位为亿元；按全市或全州行政范围直接读取，标准化为亿元并保留两位小数。",
        "lineage_selection_reason": "官方财政文件明确披露年度全市/全州政府性基金收入；不使用市本级、预算数、区县数或图表估读值。",
        "note": note,
    }


OFFICIAL_2024_CITY_FUND_GAP_SOURCES = (
    _source(
        city_name="福州市", city_id="CN-350100", slug="FUZHOU",
        url="https://www.fuzhou.gov.cn/zgfzzt/czzj/bjndyjs/zfjsgk/202507/t20250711_5046383.htm",
        source_path="fuzhou_2024_fiscal_fund_gap_excerpt.txt",
        excerpt_path="fuzhou_2024_fiscal_fund_gap_excerpt.txt",
        document_title="2024年度福州市财政决算收支情况",
        publisher="福州市财政局", publication_date="2025-07-11", source_format="html",
        data_status="final",
        patterns={"gov_fund_revenue_100m": r"城市=福州市｜年度=2024｜全市政府性基金预算收入=([0-9.]+)亿元"},
        page_number="官方网页“一、全市财政决算收支情况”正文",
        source_locator="官方网页；年度=2024；行政范围=全市；政府性基金预算收入",
        note="采用福州市全市财政决算中的政府性基金预算收入612.28亿元。",
    ),
    _source(
        city_name="阜新市", city_id="CN-210900", slug="FUXIN",
        url="https://czj.fuxin.gov.cn/content/2025/1006451.html",
        source_path="fuxin_2024_fiscal_fund_gap_excerpt.txt",
        excerpt_path="fuxin_2024_fiscal_fund_gap_excerpt.txt",
        document_title="2024年阜新市财政决算报告",
        publisher="阜新市财政局", publication_date="2025-08-29", source_format="html",
        data_status="final",
        patterns={"gov_fund_revenue_100m": r"城市=阜新市｜年度=2024｜全市政府性基金预算收入实际完成=([0-9.]+)亿元"},
        page_number="官方网页财政决算报告正文",
        source_locator="官方网页；年度=2024；行政范围=全市；政府性基金预算收入实际完成",
        note="采用阜新市全市政府性基金预算收入实际完成6.48亿元，不使用批准预算数16.28亿元。",
    ),
    _source(
        city_name="台州市", city_id="CN-331000", slug="TAIZHOU",
        url="https://www.zjtz.gov.cn/module/download/downfile.jsp?classid=0&filename=b49cc0874e5f4cd89c0dd0a0e007972e.pdf",
        source_path="taizhou_2024_fiscal_fund_gap_excerpt.txt",
        excerpt_path="taizhou_2024_fiscal_fund_gap_excerpt.txt",
        document_title="2024年全市政府性基金预算收入执行情况表",
        publisher="台州市财政局/台州市人民代表大会", publication_date="2025-02-28", source_format="pdf",
        data_status="execution",
        patterns={"gov_fund_revenue_100m": r"城市=台州市｜年度=2024｜全市政府性基金预算收入执行数=([0-9.]+)亿元"},
        page_number="PDF《2024年全市政府性基金预算收入执行情况表》总计行",
        source_locator="官方预算表；年度=2024；行政范围=全市；政府性基金预算收入执行数",
        note="表格总计为4909578万元，按原始单位换算并保留两位小数为490.96亿元。",
    ),
    _source(
        city_name="保山市", city_id="CN-530500", slug="BAOSHAN",
        url="https://baoshan.gov.cn/virtual_attach_file.vsb?afc=OLmCxanmGaLzC4oJRlbMlCZUlCYMRA0kM7MVo7V2ozWkMRC0gihFp2hmCIa0MkhkLkyYUYyYUlr2LzMfM774U8C8U4vDLmUYLRv4L47ZMm6FnR98L7-PMzWFM4UPUmvJv2nto40N0bsTOpdTJ--YLR-8bpt8bQYabXqbEgS1bXSBEqH7bEE5bwtjEH2LbwoVbCqibQHLLmGYM_IbxoIvOoqIJ_18wJql03t1Ao_JT33y1o1M1_qA1o3y1_3y1oIVKoIy9o_W1o3y1z-aLmlaLz-YLRLPozlboRLZgjfNQmOeCjM4vtiEQtiw6swYLR-YgDTJQty0MRC4L1yPLR74Mm7sMkbw62a8c",
        source_path="baoshan_2024_fiscal_fund_gap_excerpt.txt",
        excerpt_path="baoshan_2024_fiscal_fund_gap_excerpt.txt",
        document_title="保山市2024年地方财政预算执行情况和2025年地方财政预算（草案）",
        publisher="保山市财政局", publication_date="2025-02-18", source_format="pdf",
        data_status="execution",
        patterns={"gov_fund_revenue_100m": r"城市=保山市｜年度=2024｜全市政府性基金预算收入执行数=([0-9.]+)亿元"},
        page_number="PDF政府性基金预算收入执行情况表总计行",
        source_locator="官方预算报告；年度=2024；行政范围=全市；政府性基金预算收入执行数",
        note="表格执行数为202386万元，标准化为20.24亿元。",
    ),
    _source(
        city_name="南充市", city_id="CN-511300", slug="NANCHONG",
        url="https://www.ncjggw.gov.cn/shows/123/18720.html",
        source_path="nanchong_2024_fiscal_fund_gap_excerpt.txt",
        excerpt_path="nanchong_2024_fiscal_fund_gap_excerpt.txt",
        document_title="关于南充市2024年预算执行情况和2025年预算草案的报告",
        publisher="南充市财政局", publication_date="2025-02-25", source_format="html",
        data_status="execution",
        patterns={"gov_fund_revenue_100m": r"城市=南充市｜年度=2024｜全市政府性基金收入=([0-9.]+)亿元"},
        page_number="官方网页预算报告正文",
        source_locator="官方预算报告；年度=2024；行政范围=全市；政府性基金收入",
        note="报告明确披露全市政府性基金收入148.1亿元。",
    ),
    _source(
        city_name="宝鸡市", city_id="CN-610300", slug="BAOJI",
        url="https://www.baoji.gov.cn/col9816/col9818/col9845/col9847/202503/P020250306619675554123.pdf",
        source_path="baoji_2024_fiscal_fund_gap_excerpt.txt",
        excerpt_path="baoji_2024_fiscal_fund_gap_excerpt.txt",
        document_title="关于宝鸡市2024年财政预算执行情况和2025年财政预算草案的报告",
        publisher="宝鸡市财政局", publication_date="2025-03-06", source_format="pdf",
        data_status="execution",
        patterns={"gov_fund_revenue_100m": r"城市=宝鸡市｜年度=2024｜全市政府性基金收入=([0-9.]+)亿元"},
        page_number="PDF财政预算执行情况报告政府性基金段",
        source_locator="官方预算报告；年度=2024；行政范围=全市；政府性基金收入",
        note="采用全市政府性基金收入37.75亿元，不使用市本级收入27.91亿元。",
    ),
    _source(
        city_name="安康市", city_id="CN-610900", slug="ANKANG",
        url="https://www.ankang.gov.cn/UploadFiles/file/20250218/20250218093607_3396.pdf",
        source_path="ankang_2024_fiscal_fund_gap_excerpt.txt",
        excerpt_path="ankang_2024_fiscal_fund_gap_excerpt.txt",
        document_title="关于安康市2024年财政预算执行情况和2025年财政预算草案的报告",
        publisher="安康市财政局", publication_date="2025-02-18", source_format="pdf",
        data_status="execution",
        patterns={"gov_fund_revenue_100m": r"城市=安康市｜年度=2024｜全市政府性基金收入=([0-9.]+)亿元"},
        page_number="PDF预算报告政府性基金预算执行情况表",
        source_locator="官方预算报告；年度=2024；行政范围=全市；政府性基金收入",
        note="表格总计为377194万元，标准化为37.72亿元。",
    ),
    _source(
        city_name="榆林市", city_id="CN-610800", slug="YULIN",
        url="https://www.yl.gov.cn/zwgk/fdzdgknr/czxx/czyjs/szfczys/202505/P020250703576007878613.pdf",
        source_path="yulin_2024_fiscal_fund_gap_excerpt.txt",
        excerpt_path="yulin_2024_fiscal_fund_gap_excerpt.txt",
        document_title="关于榆林市2024年财政预算执行情况和2025年预算草案的报告",
        publisher="榆林市财政局", publication_date="2025-05-30", source_format="pdf",
        data_status="execution",
        patterns={"gov_fund_revenue_100m": r"城市=榆林市｜年度=2024｜全市政府性基金收入=([0-9.]+)亿元"},
        page_number="PDF预算报告政府性基金预算收入表",
        source_locator="官方预算报告；年度=2024；行政范围=全市；政府性基金收入",
        note="政府性基金收入原表为762026万元，标准化为76.20亿元；不采用收入合计783605万元。",
    ),
    _source(
        city_name="阿坝藏族羌族自治州", city_id="CN-513200", slug="ABA",
        url="https://www.abrd.gov.cn/zrdcwh/c104573/202512/09beff2312904c28b3735a97efe09865.shtml",
        source_path="aba_2024_fiscal_fund_gap_excerpt.txt",
        excerpt_path="aba_2024_fiscal_fund_gap_excerpt.txt",
        document_title="阿坝州2024年财政决算和2025年1至6月财政预算执行情况的报告",
        publisher="阿坝藏族羌族自治州财政局/州人大常委会", publication_date="2025-08-28", source_format="html",
        data_status="final",
        patterns={"gov_fund_revenue_100m": r"城市=阿坝藏族羌族自治州｜年度=2024｜全州政府性基金预算收入=([0-9.]+)亿元"},
        page_number="官方网页财政决算报告正文",
        source_locator="官方决算报告；年度=2024；行政范围=全州；政府性基金预算收入",
        note="报告明确披露全州政府性基金预算收入11.4亿元。",
    ),
    _source(
        city_name="商洛市", city_id="CN-611000", slug="SHANGLUO",
        url="https://www.shangluo.gov.cn/__local/3/A7/CC/24A02E3BAE184552717016E42D1_D7E34652_ABC635.pdf",
        source_path="shangluo_2024_fiscal_fund_gap_excerpt.txt",
        excerpt_path="shangluo_2024_fiscal_fund_gap_excerpt.txt",
        document_title="关于商洛市2024年预算执行情况和2025年预算草案的报告",
        publisher="商洛市财政局", publication_date="2025-02-27", source_format="pdf",
        data_status="execution",
        patterns={"gov_fund_revenue_100m": r"城市=商洛市｜年度=2024｜全市政府性基金收入=([0-9.]+)亿元"},
        page_number="PDF预算报告政府性基金收入段",
        source_locator="官方预算报告；年度=2024；行政范围=全市；政府性基金收入",
        note="报告明确披露全市政府性基金收入13.1亿元。",
    ),
)


__all__ = ["OFFICIAL_2024_CITY_FUND_GAP_SOURCES"]
