#!/usr/bin/env python3
"""独立校验全国面板 CSV/XLSX 导出结果。"""

from __future__ import annotations

import argparse
import csv
import json
import zipfile
from decimal import Decimal, InvalidOperation
from pathlib import Path

try:
    from scripts.data_quality import OFFICIAL_DEBT_EXCEPTION_STATUS
except ModuleNotFoundError:
    from data_quality import OFFICIAL_DEBT_EXCEPTION_STATUS

START_YEAR = 2018
END_YEAR = 2026
NUMERIC_FIELDS = {
    "gdp_current_100m",
    "gdp_real_growth_pct",
    "resident_population_10k",
    "general_public_revenue_100m",
    "general_public_expenditure_100m",
    "gov_fund_revenue_100m",
    "general_debt_limit_100m",
    "general_debt_balance_100m",
    "special_debt_limit_100m",
    "special_debt_balance_100m",
    "statutory_debt_limit_100m",
    "statutory_debt_balance_100m",
    "debt_limit_utilization_pct",
    "statutory_debt_to_gdp_pct",
    "statutory_debt_to_revenue_pct",
    "statutory_debt_to_general_revenue_pct",
    "fiscal_self_sufficiency_pct",
    "fund_revenue_dependence_pct",
    "gov_fund_to_general_revenue_pct",
}


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        return list(csv.DictReader(handle))


def decimal_or_none(value: str) -> Decimal | None:
    if value in (None, ""):
        return None
    try:
        return Decimal(value)
    except (InvalidOperation, ValueError) as exc:
        raise AssertionError(f"数值字段无法解析为 Decimal：{value!r}") from exc


def provisional_source_grade_error(row: dict[str, str]) -> str | None:
    """provisional 只要求声明来源等级，不把 B1/B2 错判为低等级。"""

    if row.get("data_status") == "provisional" and not str(row.get("source_grade") or "").strip():
        return f"provisional 值来源等级未明确：{row.get('city_id', '')}-{row.get('metric_year', '')}"
    return None


def validate(input_dir: Path, require_statutory_debt_gate: bool = False) -> dict[str, object]:
    dim = read_csv(input_dir / "dim_city.csv")
    macro = read_csv(input_dir / "city_macro_fiscal.csv")
    debt = read_csv(input_dir / "city_gov_debt.csv")
    lineage = read_csv(input_dir / "field_lineage.csv")
    calculations = read_csv(input_dir / "calculation_lineage.csv")
    sources = read_csv(input_dir / "source_document.csv")
    collection = read_csv(input_dir / "collection_status.csv")
    evidence_missing = read_csv(input_dir / "evidence_based_missing.csv") if (input_dir / "evidence_based_missing.csv").exists() else []
    errors: list[str] = []

    dim_keys = [(row.get("city_id"), row.get("metric_year")) for row in dim]
    macro_keys = [(row.get("city_id"), row.get("metric_year")) for row in macro]
    if len(dim_keys) != len(set(dim_keys)):
        errors.append("dim_city 年度主键重复")
    if len(macro_keys) != len(set(macro_keys)):
        errors.append("city_macro_fiscal 年度主键重复")
    if set(dim_keys) != set(macro_keys):
        errors.append("城市主表与经济财政表的城市年度键不一致")
    if not all(row.get("city_id") and row.get("city_name_cn") and row.get("province_name") for row in dim):
        errors.append("城市主表存在身份字段空值")
    if not all(START_YEAR <= int(row["metric_year"]) <= END_YEAR for row in dim):
        errors.append("城市主表年度超出 2018—2026")

    lineage_by_target: dict[tuple[str, str], list[dict[str, str]]] = {}
    calc_by_target: dict[tuple[str, str], list[dict[str, str]]] = {}
    for item in lineage:
        lineage_by_target.setdefault((item.get("target_record_id", ""), item.get("target_field", "")), []).append(item)
    for item in calculations:
        calc_by_target.setdefault((item.get("target_record_id", ""), item.get("target_field", "")), []).append(item)

    macro_fields = [field for field in NUMERIC_FIELDS if field in (macro[0] if macro else {})]
    for row in macro:
        for field in macro_fields:
            decimal_or_none(row.get(field, ""))
            if row.get(field, "") != "":
                target = (f"MACRO-{row['city_id']}-{row['metric_year']}-PREFECTURE", field)
                if target not in lineage_by_target:
                    errors.append(f"非空业务字段缺少 field_lineage：{target}")
                if field.endswith("pct") or field.startswith("statutory_debt_"):
                    # statutory totals and ratios are generated by formula in this snapshot;
                    # directly disclosed values also have calculation lineage when recalculated.
                    if field in {"statutory_debt_limit_100m", "statutory_debt_balance_100m", "debt_limit_utilization_pct", "statutory_debt_to_gdp_pct", "statutory_debt_to_revenue_pct", "statutory_debt_to_general_revenue_pct", "fiscal_self_sufficiency_pct", "fund_revenue_dependence_pct", "gov_fund_to_general_revenue_pct"} and target not in calc_by_target:
                        errors.append(f"计算字段缺少 calculation_lineage：{target}")

    for row in debt:
        limit = decimal_or_none(row.get("statutory_debt_limit_100m", ""))
        balance = decimal_or_none(row.get("statutory_debt_balance_100m", ""))
        if (
            limit is not None
            and balance is not None
            and balance > limit + Decimal("0.2")
            and row.get("data_status") != OFFICIAL_DEBT_EXCEPTION_STATUS
        ):
            errors.append(f"法定债务余额超过限额：{row['record_id']}")

    for row in macro:
        if row.get("data_status") == "missing_zero":
            errors.append(f"发现缺失伪零状态：{row['city_id']}-{row['metric_year']}")
        grade_error = provisional_source_grade_error(row)
        if grade_error:
            errors.append(grade_error)

    source_ids = {row.get("source_doc_id") for row in sources}
    for item in evidence_missing:
        if item.get("collection_status") != "evidence_based_missing":
            errors.append(f"证据化缺失记录状态错误：{item.get('city_id')}-{item.get('metric_year')}")
        for source_id in str(item.get("evidence_source_doc_ids") or "").split(";"):
            if source_id and source_id not in source_ids:
                errors.append(f"证据化缺失记录指向不存在的来源：{item.get('city_id')}-{item.get('metric_year')}-{source_id}")
    for row in lineage:
        if row.get("value_origin") != "calculated" and row.get("source_doc_id") not in source_ids:
            errors.append(f"字段血缘指向不存在的来源：{row.get('lineage_id')}")
        if row.get("value_origin") == "calculated" and not row.get("calculation_id"):
            errors.append(f"计算血缘缺少 calculation_id：{row.get('lineage_id')}")

    gate_years = set(range(2018, 2026))
    target_keys = {(row.get("city_id"), row.get("metric_year")) for row in dim if int(row.get("metric_year", "0")) in gate_years}
    debt_by_key = {(row.get("city_id"), row.get("metric_year")): row for row in debt}
    missing_gate_keys = sorted(
        key for key in target_keys
        if not debt_by_key.get(key, {}).get("statutory_debt_balance_100m")
    )
    gate = {
        "name": "全国地级行政单元 2018—2025 法定政府债务余额 100% 覆盖",
        "target_key_count": len(target_keys),
        "covered_key_count": len(target_keys) - len(missing_gate_keys),
        "missing_key_count": len(missing_gate_keys),
        "passed": not missing_gate_keys,
        "missing_keys_sample": [f"{city_id}-{year}" for city_id, year in missing_gate_keys[:200]],
    }
    if require_statutory_debt_gate and missing_gate_keys:
        errors.append(f"未达到法定债务余额硬门槛：缺少 {len(missing_gate_keys)} 个城市年度键（2018—2025）")

    required_files = [
        "dim_city.csv", "city_macro_fiscal.csv", "city_gov_debt.csv", "lgfv_company.csv",
        "lgfv_financial.csv", "bond_detail.csv", "bond_special_term.csv", "bond_proceeds_allocation.csv",
        "credit_event.csv", "source_document.csv", "field_lineage.csv", "manual_review_decision.csv",
        "calculation_lineage.csv", "formula_registry.csv", "formula_dependency.csv", "risk_metric.csv",
        "collection_status.csv", "evidence_based_missing.csv", "README_数据说明.md", "quality_report.json",
    ]
    missing_files = [name for name in required_files if not (input_dir / name).exists()]
    errors.extend(f"缺少输出文件：{name}" for name in missing_files)

    result = {
        "passed": not errors,
        "errors": errors,
        "counts": {
            "dim_city": len(dim),
            "city_macro_fiscal": len(macro),
            "city_gov_debt": len(debt),
            "field_lineage": len(lineage),
            "calculation_lineage": len(calculations),
            "source_document": len(sources),
            "collection_status": len(collection),
            "evidence_based_missing": len(evidence_missing),
        },
        "coverage": {
            "gdp_current_100m": sum(bool(row.get("gdp_current_100m")) for row in macro) / len(macro) if macro else 0,
            "general_public_revenue_100m": sum(bool(row.get("general_public_revenue_100m")) for row in macro) / len(macro) if macro else 0,
            "statutory_debt_balance_100m": sum(bool(row.get("statutory_debt_balance_100m")) for row in macro) / len(macro) if macro else 0,
        },
        "delivery_gate": gate,
    }
    return result


def validate_xlsx(input_dir: Path) -> list[str]:
    errors: list[str] = []
    xlsx_files = list(input_dir.glob("*.xlsx"))
    if not xlsx_files:
        return ["未找到 XLSX 工作簿"]
    with zipfile.ZipFile(xlsx_files[0]) as archive:
        names = set(archive.namelist())
        if "xl/workbook.xml" not in names:
            errors.append("XLSX 缺少 xl/workbook.xml")
        if "[Content_Types].xml" not in names:
            errors.append("XLSX 缺少 [Content_Types].xml")
    return errors


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input-dir", required=True)
    parser.add_argument("--check-xlsx", action="store_true")
    parser.add_argument("--require-statutory-debt-2018-2025", action="store_true")
    args = parser.parse_args()
    input_dir = Path(args.input_dir)
    result = validate(input_dir, require_statutory_debt_gate=args.require_statutory_debt_2018_2025)
    if args.check_xlsx:
        result["errors"] = list(result["errors"]) + validate_xlsx(input_dir)
        result["passed"] = not result["errors"]
    print(json.dumps(result, ensure_ascii=False, indent=2))
    raise SystemExit(0 if result["passed"] else 1)


if __name__ == "__main__":
    main()
