"""云南 2018—2020 年低等级 GDP 实际增速的可定位来源批次。"""

from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
EXCERPT_PATH = (
    ROOT
    / "raw"
    / "province_fiscal"
    / "yunnan"
    / "yearbook"
    / "yunnan_growth_sources_excerpt.txt"
)


def _source(
    *,
    year: int,
    city_name: str,
    city_id: str,
    growth: str,
    url: str,
    document_title: str,
    publisher: str,
    publisher_level: str,
    publication_date: str,
    source_grade: str,
    source_format: str,
    page_number: str,
    note: str,
) -> dict:
    return {
        "year": year,
        "city_name": city_name,
        "city_id": city_id,
        "source_doc_id": f"SRC-{source_grade}-YUNNAN-GDP-GROWTH-{year}-{city_id}",
        "url": url,
        "landing_page_url": url,
        "attachment_url": url,
        "path": EXCERPT_PATH,
        "text_path": EXCERPT_PATH,
        "text_is_curated": True,
        "document_title": document_title,
        "publisher": publisher,
        "publisher_level": publisher_level,
        "publication_date": publication_date,
        "source_grade": source_grade,
        "expected_grade": source_grade,
        "source_format": source_format,
        "data_status": "reported",
        "data_status_label": f"{year}年GDP实际增速公开报告值",
        "document_type": "州级国民经济和社会发展统计公报或官方经济回顾",
        "page_number": page_number,
        "title_source": "official_statement_or_precise_repost",
        "access_status": "入口页或公开附件及精确摘录已归档",
        "raw_unit": "%",
        "raw_units": {"gdp_real_growth_pct": "%"},
        "table_name": document_title,
        "lineage_locator_type": (
            "html_text_statement" if source_format == "html" else "pdf_text_statement"
        ),
        "lineage_extraction_method": (
            "curated-official-html-gdp-growth-parser"
            if source_format == "html"
            else "curated-official-pdf-gdp-growth-parser"
        ),
        "lineage_normalization_rule": (
            "官方或精确公开来源原始单位为%；数值直接读取，保留两位小数；"
            "GDP增速按可比价格/可比价口径，不把名义变化率代入；全州口径。"
        ),
        "lineage_selection_reason": (
            f"{source_grade}来源明确披露{year}年{city_name}全州 GDP实际增速，"
            "可定位到统计公报正文、官方经济回顾或精确历史表；按可比口径接入。"
        ),
        "patterns": {
            "gdp_real_growth_pct": (
                rf"城市={re.escape(city_name)}｜年度={year}｜"
                rf"GDP增速=([0-9.]+)%"
            )
        },
        "source_locator": (
            f"{EXCERPT_PATH.relative_to(ROOT)}；来源={url}；"
            f"城市={city_name}；年度={year}；行政范围=全州；"
            f"原始报告定位={page_number}"
        ),
        "note": f"{note} 数据按可比口径，行政范围为全州。",
        "expected_value": growth,
    }


YUNNAN_GDP_GROWTH_SOURCES = (
    _source(
        year=2018,
        city_name="楚雄彝族自治州",
        city_id="CN-532300",
        growth="10.2",
        url="https://www.cxz.gov.cn/info/egovinfo/1001/xxgkxt_content/115323000151673132-/2022-08130014.htm",
        document_title="楚雄州‘十三五’规划纲要主要指标完成情况及经济发展回顾",
        publisher="楚雄彝族自治州人民政府",
        publisher_level="州级政府门户官方信息公开页",
        publication_date="2022-08-13",
        source_grade="A2",
        source_format="html",
        page_number="官方网页经济发展回顾及2016—2020年增速表",
        note="A2州级政府官方回顾页，明确列示2018年全州 GDP 按可比口径的实际增速；行政范围=全州。",
    ),
    _source(
        year=2019,
        city_name="楚雄彝族自治州",
        city_id="CN-532300",
        growth="9.1",
        url="https://www.cxz.gov.cn/info/egovinfo/1001/xxgkxt_content/115323000151673132-/2022-08130014.htm",
        document_title="楚雄州‘十三五’规划纲要主要指标完成情况及经济发展回顾",
        publisher="楚雄彝族自治州人民政府",
        publisher_level="州级政府门户官方信息公开页",
        publication_date="2022-08-13",
        source_grade="A2",
        source_format="html",
        page_number="官方网页经济发展回顾及2016—2020年增速表",
        note="A2州级政府官方回顾页，明确列示2019年全州 GDP 按可比口径的实际增速；行政范围=全州。",
    ),
    _source(
        year=2020,
        city_name="楚雄彝族自治州",
        city_id="CN-532300",
        growth="6.0",
        url="https://www.cxz.gov.cn/info/egovinfo/1001/xxgkxt_content/115323000151673132-/2022-08130014.htm",
        document_title="楚雄州‘十三五’规划纲要主要指标完成情况及经济发展回顾",
        publisher="楚雄彝族自治州人民政府",
        publisher_level="州级政府门户官方信息公开页",
        publication_date="2022-08-13",
        source_grade="A2",
        source_format="html",
        page_number="官方网页经济发展回顾及2016—2020年增速表",
        note="A2州级政府官方回顾页，明确列示2020年全州 GDP 按可比口径的实际增速；行政范围=全州。",
    ),
    _source(
        year=2018,
        city_name="红河哈尼族彝族自治州",
        city_id="CN-532500",
        growth="9.7",
        url="https://www.hh.gov.cn/hhzrmzfgb/2025ngb/honghezhourenminzhengfugongbao2025niandi2qi.pdf",
        document_title="红河州人民政府公报2025年第2期州十三届人大第五次会议专题文件",
        publisher="红河哈尼族彝族自治州人民政府",
        publisher_level="州级政府公报官方附件",
        publication_date="2025-06-30",
        source_grade="A2",
        source_format="pdf",
        page_number="PDF图1及下方2015—2024年历史数据表",
        note="A2州级政府公报官方附件，历史图表精确列示2018年全州 GDP 按可比口径的实际增速；行政范围=全州。",
    ),
    _source(
        year=2019,
        city_name="红河哈尼族彝族自治州",
        city_id="CN-532500",
        growth="8.5",
        url="https://www.hh.gov.cn/hhzrmzfgb/2025ngb/honghezhourenminzhengfugongbao2025niandi2qi.pdf",
        document_title="红河州人民政府公报2025年第2期州十三届人大第五次会议专题文件",
        publisher="红河哈尼族彝族自治州人民政府",
        publisher_level="州级政府公报官方附件",
        publication_date="2025-06-30",
        source_grade="A2",
        source_format="pdf",
        page_number="PDF图1及下方2015—2024年历史数据表",
        note="A2州级政府公报官方附件，历史图表精确列示2019年全州 GDP 按可比口径的实际增速；行政范围=全州。",
    ),
    _source(
        year=2020,
        city_name="红河哈尼族彝族自治州",
        city_id="CN-532500",
        growth="5.2",
        url="https://www.hh.gov.cn/hhzrmzfgb/2025ngb/honghezhourenminzhengfugongbao2025niandi2qi.pdf",
        document_title="红河州人民政府公报2025年第2期州十三届人大第五次会议专题文件",
        publisher="红河哈尼族彝族自治州人民政府",
        publisher_level="州级政府公报官方附件",
        publication_date="2025-06-30",
        source_grade="A2",
        source_format="pdf",
        page_number="PDF图1及下方2015—2024年历史数据表",
        note="A2州级政府公报官方附件，历史图表精确列示2020年全州 GDP 按可比口径的实际增速；行政范围=全州。",
    ),
    _source(
        year=2018,
        city_name="文山壮族苗族自治州",
        city_id="CN-532600",
        growth="10.3",
        url="https://web.xiaze.org/tjgb/201905/57528.html",
        document_title="文山州2018年国民经济和社会发展统计公报",
        publisher="文山州统计局（精确公开转载）",
        publisher_level="州级统计公报精确转载",
        publication_date="2019-05-31",
        source_grade="B2",
        source_format="html",
        page_number="正文‘一、综合’",
        note="B2精确公开转载，正文明确2018年全州 GDP 按可比口径的实际增速；行政范围=全州。",
    ),
    _source(
        year=2019,
        city_name="文山壮族苗族自治州",
        city_id="CN-532600",
        growth="10.1",
        url="https://travel.yunnan.cn/system/2020/06/11/030711598.shtml",
        document_title="文山州2019年经济社会发展数据公开页",
        publisher="云南网（文山州统计公报数据精确公开）",
        publisher_level="省级媒体精确转载",
        publication_date="2020-06-11",
        source_grade="B2",
        source_format="html",
        page_number="GDP数据段",
        note="B2精确公开页，明确2019年文山州全州 GDP 按可比口径的实际增速；行政范围=全州。",
    ),
    _source(
        year=2020,
        city_name="文山壮族苗族自治州",
        city_id="CN-532600",
        growth="5.4",
        url="https://www.ynws.gov.cn/wszzf/ndq120/1855113623615401984/qFaoAHQc.pdf",
        document_title="文山州人民政府公报2020年国民经济和社会发展统计公报",
        publisher="文山壮族苗族自治州人民政府、文山州统计局",
        publisher_level="州级政府公报官方附件",
        publication_date="2021-04-30",
        source_grade="A2",
        source_format="pdf",
        page_number="PDF正文‘一、综合’",
        note="A2州级政府公报官方附件，明确2020年全州 GDP 按可比口径的实际增速；行政范围=全州。",
    ),
    _source(
        year=2018,
        city_name="西双版纳傣族自治州",
        city_id="CN-532800",
        growth="8.1",
        url="https://www.gcs66.com/document_detail/7147.html",
        document_title="西双版纳州2018年国民经济和社会发展统计公报",
        publisher="西双版纳州统计局、国家统计局西双版纳调查队（精确公开转载）",
        publisher_level="统计公报精确转载",
        publication_date="2021-10-09",
        source_grade="B2",
        source_format="html",
        page_number="正文‘一、综合’",
        note="B2精确公开转载，正文明确2018年全州 GDP 按可比口径的同比实际增速；行政范围=全州。",
    ),
    _source(
        year=2019,
        city_name="西双版纳傣族自治州",
        city_id="CN-532800",
        growth="10.1",
        url="https://www.quyushuju.com/forum.php?mod=viewthread&page=1&tid=54161",
        document_title="西双版纳州2019年国民经济和社会发展统计公报",
        publisher="西双版纳州统计局、国家统计局西双版纳调查队（精确公开转载）",
        publisher_level="统计公报精确转载",
        publication_date="2021-08-13",
        source_grade="B2",
        source_format="html",
        page_number="正文‘一、综合’",
        note="B2精确公开转载，正文明确2019年全州 GDP 按可比口径的同比实际增速；行政范围=全州。",
    ),
    _source(
        year=2020,
        city_name="西双版纳傣族自治州",
        city_id="CN-532800",
        growth="3.6",
        url="https://web.xiaze.org/tjgb/202203/60673.html",
        document_title="西双版纳州2020年国民经济和社会发展统计公报",
        publisher="西双版纳州统计局、国家统计局西双版纳调查队（精确公开转载）",
        publisher_level="统计公报精确转载",
        publication_date="2021-04-30",
        source_grade="B2",
        source_format="html",
        page_number="正文‘一、综合’",
        note="B2精确公开转载，正文明确2020年全州 GDP 按可比口径的同比实际增速；行政范围=全州。",
    ),
    _source(
        year=2018,
        city_name="大理白族自治州",
        city_id="CN-532900",
        growth="9.3",
        url="https://www.dali.gov.cn/dlzrmzf/xxgkml/c108766/pc/content/1971447967914233856/content_1971447967914233856.html",
        document_title="关于大理白族自治州2018年国民经济和社会发展计划执行情况的报告",
        publisher="大理白族自治州发展和改革委员会、大理白族自治州人民政府",
        publisher_level="州级政府官方信息公开页",
        publication_date="2019-02-23",
        source_grade="A2",
        source_format="html",
        page_number="正文第44行‘一、2018年国民经济和社会发展计划执行情况’",
        note="A2州级政府官方报告，明确2018年全州 GDP 同比实际增速；行政范围=全州。",
    ),
    _source(
        year=2019,
        city_name="大理白族自治州",
        city_id="CN-532900",
        growth="6.1",
        url="https://www.dali.gov.cn/dlzrmzf/c101526/pc/content/1968879938755989504/content_1968879938755989504.html",
        document_title="2020年大理州人民政府工作报告",
        publisher="大理白族自治州人民政府",
        publisher_level="州级政府官方工作报告",
        publication_date="2020-05-17",
        source_grade="A2",
        source_format="html",
        page_number="报告正文2019年经济社会发展回顾段",
        note="A2州级政府官方工作报告，明确2019年全州 GDP 实际增速；行政范围=全州。",
    ),
    _source(
        year=2018,
        city_name="德宏傣族景颇族自治州",
        city_id="CN-533100",
        growth="8.0",
        url="https://www.dhms.gov.cn/tjj/Attach/2403/28D01W0W7K2403141544450341C6DE.pdf",
        document_title="德宏州统计年鉴2018",
        publisher="德宏傣族景颇族自治州统计局",
        publisher_level="州级统计机构官方年鉴附件",
        publication_date="2019-12-31",
        source_grade="A2",
        source_format="pdf",
        page_number="GDP表德宏州全域行",
        note="A2州级统计年鉴官方 PDF，GDP表精确列示2018年全州 GDP 按可比口径的实际增速；行政范围=全州。",
    ),
    _source(
        year=2019,
        city_name="德宏傣族景颇族自治州",
        city_id="CN-533100",
        growth="7.9",
        url="https://www.dh.gov.cn/tjj/Web/_F0_0_04K66UIFKB45QH0AM8TO740R1R.htm",
        document_title="德宏州2019年国民经济和社会发展统计公报",
        publisher="德宏傣族景颇族自治州统计局、德宏州人民政府",
        publisher_level="州级政府官方统计公报",
        publication_date="2020-04-30",
        source_grade="A2",
        source_format="html",
        page_number="正文‘一、经济增长’",
        note="A2州级政府官方统计公报，明确2019年全州 GDP 同比实际增速；行政范围=全州。",
    ),
    _source(
        year=2018,
        city_name="怒江傈僳族自治州",
        city_id="CN-533300",
        growth="12.1",
        url="https://web.xiaze.org/tjgb/201905/57583.html",
        document_title="怒江州2018年国民经济和社会发展统计公报",
        publisher="怒江州统计局、国家统计局怒江调查队（精确公开转载）",
        publisher_level="统计公报精确转载",
        publication_date="2019-05-31",
        source_grade="B2",
        source_format="html",
        page_number="正文‘一、综合’",
        note="B2精确公开转载，正文明确2018年全州 GDP 可比实际增速；行政范围=全州。",
    ),
    _source(
        year=2019,
        city_name="怒江傈僳族自治州",
        city_id="CN-533300",
        growth="11.1",
        url="https://www.sse.com.cn/disclosure/bond/announcement/corporate/c/2021-03-15/4120939558796868546199009.pdf",
        document_title="开远市兴远开发投资集团公开披露报告云南州市经济指标表",
        publisher="上海证券交易所公开披露、评级报告整理",
        publisher_level="交易所公开披露的B2精确表格来源",
        publication_date="2021-03-15",
        source_grade="B2",
        source_format="pdf",
        page_number="云南州市历史 GDP 增速表",
        note="B2交易所公开披露报告中的精确表格，列示2019年怒江州全州 GDP 按可比口径的实际增速；行政范围=全州。",
    ),
    _source(
        year=2020,
        city_name="怒江傈僳族自治州",
        city_id="CN-533300",
        growth="7.1",
        url="https://tjgb.hongheiku.com/14302.html",
        document_title="怒江州2020年国民经济和社会发展统计公报",
        publisher="怒江州统计局、国家统计局怒江调查队（精确公开转载）",
        publisher_level="统计公报精确转载",
        publication_date="2021-01-29",
        source_grade="B2",
        source_format="html",
        page_number="正文‘一、综合’",
        note="B2精确公开转载，正文明确2020年全州 GDP 可比实际增速；行政范围=全州。",
    ),
    _source(
        year=2018,
        city_name="迪庆藏族自治州",
        city_id="CN-533400",
        growth="9.5",
        url="https://web.xiaze.org/tjgb/201907/57700.html",
        document_title="迪庆州2018年国民经济和社会发展统计公报",
        publisher="迪庆州统计局（精确公开转载）",
        publisher_level="统计公报精确转载",
        publication_date="2019-07-31",
        source_grade="B2",
        source_format="html",
        page_number="正文‘一、综合’",
        note="B2精确公开转载，正文明确2018年全州 GDP 按可比价计算的实际增速；行政范围=全州。",
    ),
    _source(
        year=2019,
        city_name="迪庆藏族自治州",
        city_id="CN-533400",
        growth="11.6",
        url="https://www.diqing.gov.cn/xwzx/dqyw/202004/20200430_62402.html",
        document_title="迪庆藏族自治州2019年国民经济和社会发展统计公报",
        publisher="迪庆州统计局、迪庆藏族自治州人民政府",
        publisher_level="州级政府官方统计公报",
        publication_date="2020-04-30",
        source_grade="A2",
        source_format="html",
        page_number="正文‘一、综合’",
        note="A2州级政府官方统计公报，明确2019年全州 GDP 按可比价计算的实际增速；行政范围=全州。",
    ),
    _source(
        year=2020,
        city_name="迪庆藏族自治州",
        city_id="CN-533400",
        growth="5.1",
        url="https://tjgb.hongheiku.com/xjtjgb/xj2020/23622.html",
        document_title="迪庆藏族自治州2020年国民经济和社会发展统计公报",
        publisher="迪庆州统计局（精确公开转载）",
        publisher_level="统计公报精确转载",
        publication_date="2021-06-30",
        source_grade="B2",
        source_format="html",
        page_number="正文‘二、综合’",
        note="B2精确公开转载，正文明确2020年全州 GDP 按可比价计算的实际增速；行政范围=全州。",
    ),
)
